#!/bin/bash

# Build a minideb image for each supported dist

set -e
set -u
set -o pipefail

#arch=${1:-"amd64 arm64"}
arch=${1:-"loong64"}  #arch=${1:-"amd64 arm64 loong64"}

#dist="buster
#bullseye
#"
dist="buster"
for a in $arch; do
  for i in $dist; do
    ./buildone "$i" "$a"
  done
done

